services:
  - type: web
    name: maxilofacial-backend
    env: docker
    plan: free
    region: frankfurt
    dockerContext: .
    dockerfilePath: Dockerfile
    healthCheckPath: /docs
    autoDeploy: true
